### ISSUE TITLE
basic gene-plotting to-do.

### ISSUE THREAD

**Issue by brentp** [brentp/seqcover#1]
# Brent
- [x] fix coordinate translation for more edge-cases
- [ ] fix all off-by-one errors
- [x] adjust to work with bed.gz (as well as .d4)

# Mike
- [x] make transcript plot show only union plot by default and expand to all transcript on click
- [x] Show CDS Exon only by default. Toggle on UTRs and Non-CDS Exons
- [x] Sort Gene/Region Selection list
- [x] show `gene.description` somewhere.
- [x] customData should use objects instead of lists so that instead of `customdata[5]`, it uses `customdata.cdsend`
- [x] update merged transcript plot

# Joe
- [x] sort gene list by name in drop-down (taken from Mike's list)
- [x] make initial page design with nav, anchors, plot order, aesthetics
- [ ] add sample colors to table in order to remove plot legends
- [ ] add table hover events and tie them into Depth Dist per Sample plot
- [ ] fix plotly's double-click event in region plot
- [x] see if we can manipulate region plot to improve hover events

**Comment by brwnj** [comment]
stale. i think we've done our best to address these throughout the dev process.
